steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      'build',
      '--no-cache',
      '--platform',
      'linux/amd64',
      '-t', 
      'us-west2-docker.pkg.dev/${PROJECT_ID}/library/rock-paper-scissors:latest',
      '.',
    ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      'push',
      'us-west2-docker.pkg.dev/${PROJECT_ID}/library/rock-paper-scissors:latest',
    ]

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    [
      'run',
      'deploy',
      'rock-paper-scissors',
      '--image',
      'us-west2-docker.pkg.dev/${PROJECT_ID}/library/rock-paper-scissors:latest',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      "--port",
      "80",
    ]

images:
- 'us-west2-docker.pkg.dev/${PROJECT_ID}/library/rock-paper-scissors:latest'
